services:
  api:
    build: .
    ports:
      - 8000:8000
    command: uvicorn application.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
    environment:
          REDIS_HOST: redis
          REDIS_PORT: 6379
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  