services:
  - type: web
    name: shortify-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: uvicorn application.main:app --host 0.0.0.0 --port 8000 --reload
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: shortify-redis
      - key: REDIS_PORT
        value: 6379
    ports:
      - 8000

  - type: redis
    name: shortify-redis
    plan: free
