services:
  - type: web
    name: shortify-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: shortify-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: shortify-redis
          property: port

  - type: redis
    name: shortify-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all (for development only)
